version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/todo-app
permissions:
  - object: /home/ubuntu/todo-app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 6000
      runas: root
  AfterInstall:
    - location: scripts/import_variables.sh
      timeout: 6000
      runas: root
    - location: scripts/aws_region.sh
      timeout: 6000
      runas: ubuntu
    - location: scripts/install_dependencies.sh
      timeout: 6000
      runas: root
    - location: scripts/server_configuration.sh
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 6000
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 6000
      runas: root