version: 0.2

env:
  variables:
     DB_PORT: 3306
     AWS_REGION: us-east-1
  parameter-store:
    DB_NAME: "gameday-bluegreen_database_name"
    DB_USER: "gameday-bluegreen_database_user"
    DB_PASSWORD: "gameday-bluegreen_database_password"     
    DB_HOST: "gameday-bluegreen_database_host"          

phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - python --version
      - pip install --user --upgrade virtualenv
      - virtualenv -p python3 venv 
      - . venv/bin/activate
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running all unit tests"
      - venv/bin/python manage.py test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'